name: CompatHelper
on:
  push
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/compathelper-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # ssh: ${{ secrets.DOCUMENTER_KEY }}
